export enum NotificationPreferenceEvent {
  SERVICE_ORDER_UPDATED = 'SERVICE_ORDER_UPDATED',
  SERVICE_ORDER_COMMENT_CREATED = 'SERVICE_ORDER_COMMENT_CREATED',
  SERVICE_ORDER_ATTACHMENT_UPLOADED = 'SERVICE_ORDER_ATTACHMENT_UPLOADED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_COMMENT_CREATED = 'PROJECT_COMMENT_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_COMMENT_CREATED = 'TASK_COMMENT_CREATED',
  DEADLINE_ALERT = 'DEADLINE_ALERT',
  SATISFACTION_LOW_RATING = 'SATISFACTION_LOW_RATING',
  DAILY_SUMMARY = 'DAILY_SUMMARY',
}
