'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Modal } from '@/components/ui/modal';
import { apiRequest } from '@/lib/api';
import type { AuditAction, AuditExport, AuditLog, AuditLogPage } from '@/types/audit-log';

type UserOption = { id: string; name: string; email: string };
const actions: AuditAction[] = ['CREATE', 'UPDATE', 'STATUS_CHANGE', 'ASSIGN', 'COMMENT', 'ATTACHMENT', 'COMPLETE', 'CANCEL', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'SATISFACTION_SUBMITTED', 'SATISFACTION_LOW_RATING_RECEIVED', 'SATISFACTION_FOLLOWUP_UPDATED'];
const actionLabels: Record<AuditAction, string> = { CREATE: 'Criação', UPDATE: 'Atualização', DELETE: 'Exclusão', LOGIN: 'Login', LOGIN_FAILED: 'Login recusado', LOGOUT: 'Logout', STATUS_CHANGE: 'Alteração de status', COMMENT: 'Comentário', ATTACHMENT: 'Anexo', ASSIGN: 'Atribuição', COMPLETE: 'Conclusão', CANCEL: 'Cancelamento', SATISFACTION_SUBMITTED: 'Avaliação recebida', SATISFACTION_LOW_RATING_RECEIVED: 'Avaliação baixa', SATISFACTION_FOLLOWUP_UPDATED: 'Tratativa de avaliação' };
const entities = [{ value: 'ServiceOrder', label: 'Ordens de Serviço' }, { value: 'Project', label: 'Projetos' }, { value: 'Task', label: 'Tarefas' }, { value: 'DailyLog', label: 'Registros diários' }, { value: 'User', label: 'Usuários' }, { value: 'RolePermission', label: 'Permissões' }, { value: 'TenantSettings', label: 'Configurações' }, { value: 'LookupItem', label: 'Cadastros auxiliares' }, { value: 'ServiceOrderSatisfaction', label: 'Satisfação' }, { value: 'UserNotificationPreference', label: 'Notificações' }];
const empty = { entity: '', entityId: '', action: '', userId: '', startDate: '', endDate: '', search: '', criticalOnly: false };

function MetaView({ value }: { value: Record<string, unknown> }) {
  const before = value.before && typeof value.before === 'object' ? value.before as Record<string, unknown> : null;
  const after = value.after && typeof value.after === 'object' ? value.after as Record<string, unknown> : null;
  const visible = Object.entries(value).filter(([key]) => !['before', 'after'].includes(key));
  return <div className="audit-metadata">{(before || after) && <div className="audit-diff"><section><b>Antes</b><dl>{Object.entries(before ?? {}).map(([key, item]) => <div key={key}><dt>{key}</dt><dd>{String(item ?? '—')}</dd></div>)}</dl></section><section><b>Depois</b><dl>{Object.entries(after ?? {}).map(([key, item]) => <div key={key}><dt>{key}</dt><dd>{String(item ?? '—')}</dd></div>)}</dl></section></div>}{visible.length > 0 && <dl>{visible.map(([key, item]) => <div key={key}><dt>{key}</dt><dd>{typeof item === 'object' ? JSON.stringify(item) : String(item ?? '—')}</dd></div>)}</dl>}<details><summary>Dados técnicos</summary><pre>{JSON.stringify(value, null, 2)}</pre></details></div>;
}

export default function AuditLogsPage() {
  const [data, setData] = useState<AuditLogPage | null>(null); const [users, setUsers] = useState<UserOption[]>([]); const [selected, setSelected] = useState<AuditLog | null>(null);
  const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [error, setError] = useState(''); const [filters, setFilters] = useState(empty); const [applied, setApplied] = useState(empty); const [page, setPage] = useState(1);
  const queryString = useCallback((includePage = true) => { const query = new URLSearchParams(); Object.entries(applied).forEach(([key, value]) => { if (value !== '' && value !== false) query.set(key, String(value)); }); if (applied.endDate) query.set('endDate', `${applied.endDate}T23:59:59.999`); if (includePage) { query.set('page', String(page)); query.set('limit', '25'); } return query.toString(); }, [applied, page]);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await apiRequest<AuditLogPage>(`/audit-logs?${queryString()}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível carregar a auditoria.'); } finally { setLoading(false); } }, [queryString]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { apiRequest<UserOption[]>('/users').then(setUsers).catch(() => setUsers([])); }, []);
  function submit(event: FormEvent) { event.preventDefault(); setPage(1); setApplied(filters); }
  function clear() { setFilters(empty); setApplied(empty); setPage(1); }
  async function exportCsv() { setExporting(true); setError(''); try { const result = await apiRequest<AuditExport>(`/audit-logs/export?${queryString(false)}`); const blob = new Blob([`\uFEFF${result.csv}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.filename; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível exportar a auditoria.'); } finally { setExporting(false); } }
  return <>
    <header className="page-heading"><div><p className="eyebrow">Governança e rastreabilidade</p><h1>Auditoria avançada</h1><p>Investigue eventos, alterações e ações críticas do ambiente.</p></div><button className="button primary" disabled={exporting} onClick={() => void exportCsv()}>{exporting ? 'Exportando...' : 'Exportar CSV'}</button></header>
    <form className="audit-filters" onSubmit={submit}>
      <label><span>Período inicial</span><input type="date" value={filters.startDate} onChange={(e) => setFilters({ ...filters, startDate: e.target.value })} /></label><label><span>Período final</span><input type="date" value={filters.endDate} onChange={(e) => setFilters({ ...filters, endDate: e.target.value })} /></label>
      <label><span>Usuário</span><select value={filters.userId} onChange={(e) => setFilters({ ...filters, userId: e.target.value })}><option value="">Todos</option>{users.map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select></label>
      <label><span>Módulo / recurso</span><select value={filters.entity} onChange={(e) => setFilters({ ...filters, entity: e.target.value })}><option value="">Todos</option>{entities.map((entity) => <option value={entity.value} key={entity.value}>{entity.label}</option>)}</select></label>
      <label><span>Evento / ação</span><select value={filters.action} onChange={(e) => setFilters({ ...filters, action: e.target.value })}><option value="">Todos</option>{actions.map((action) => <option value={action} key={action}>{actionLabels[action]}</option>)}</select></label>
      <label><span>Entidade relacionada</span><input placeholder="ID do item" value={filters.entityId} onChange={(e) => setFilters({ ...filters, entityId: e.target.value })} /></label><label className="audit-search"><span>Texto livre</span><input placeholder="Usuário, e-mail, recurso ou ID" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /></label>
      <label className="audit-check"><input type="checkbox" checked={filters.criticalOnly} onChange={(e) => setFilters({ ...filters, criticalOnly: e.target.checked })} /><span>Somente eventos críticos</span></label><div className="audit-filter-actions"><button type="button" className="button ghost" onClick={clear}>Limpar filtros</button><button className="button primary">Aplicar filtros</button></div>
    </form>
    {error && <div className="alert error">{error}</div>}
    {data?.summary && <section className="audit-summary-grid"><article><span>Total no período</span><strong>{data.summary.totalEvents}</strong><small>eventos encontrados</small></article><article className="critical"><span>Eventos críticos</span><strong>{data.summary.criticalEvents}</strong><small>exigem atenção</small></article><article><span>Módulos mais ativos</span><strong>{data.summary.byModule[0]?.total ?? 0}</strong><small>{data.summary.byModule.slice(0, 3).map((item) => item.module).join(' · ') || 'Sem eventos'}</small></article><article><span>Usuários mais ativos</span><strong>{data.summary.activeUsers[0]?.total ?? 0}</strong><small>{data.summary.activeUsers.slice(0, 2).map((item) => item.user?.name ?? 'Sistema').join(' · ') || 'Sem eventos'}</small></article><article><span>Últimas alterações relevantes</span><strong>{data.summary.recentRelevant.length}</strong><small>{data.summary.recentRelevant[0]?.eventLabel ?? 'Sem alterações'}</small></article></section>}
    {loading ? <div className="detail-state"><span className="spinner" />Carregando auditoria...</div> : !data?.items.length ? <div className="detail-state">Nenhum evento encontrado com os filtros aplicados.</div> : <section className="audit-table-card"><div className="audit-table"><div className="audit-table-head"><span>Data e hora</span><span>Usuário</span><span>Evento</span><span>Recurso / item</span><span>Resumo</span><span /></div>{data.items.map((item) => <article key={item.id} className={item.critical ? 'is-critical' : ''}><time>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(item.createdAt))}</time><span>{item.user?.name ?? 'Sistema'}<small>{item.user?.email}</small></span><span><b className={`badge${item.critical ? ' critical' : ''}`}>{item.eventLabel}</b>{item.critical && <small>Evento crítico</small>}</span><span>{item.resourceLabel}<small>{item.entityId ?? 'Sem vínculo'}</small></span><span>{item.summary}<small>{item.ipAddress ? `IP ${item.ipAddress}` : ''}</small></span><button type="button" className="button ghost small" onClick={() => setSelected(item)}>Ver detalhes</button></article>)}</div><footer><span>{data.total} evento(s) · página {data.page} de {data.pages || 1}</span><div><button className="button ghost small" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</button><button className="button ghost small" disabled={page >= data.pages} onClick={() => setPage((value) => value + 1)}>Próxima</button></div></footer></section>}
    {selected && <Modal title={selected.eventLabel} eyebrow={selected.critical ? 'Evento crítico' : 'Detalhes da auditoria'} onClose={() => setSelected(null)}><div className="audit-detail"><dl><div><dt>Data e hora</dt><dd>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full', timeStyle: 'medium' }).format(new Date(selected.createdAt))}</dd></div><div><dt>Usuário</dt><dd>{selected.user?.name ?? 'Sistema'}</dd></div><div><dt>E-mail</dt><dd>{selected.user?.email ?? '—'}</dd></div><div><dt>Recurso</dt><dd>{selected.resourceLabel}</dd></div><div><dt>Entidade relacionada</dt><dd>{selected.entityId ?? '—'}</dd></div><div><dt>Resumo</dt><dd>{selected.summary}</dd></div></dl>{selected.metadata && Object.keys(selected.metadata).length > 0 && <MetaView value={selected.metadata} />}<details className="audit-technical"><summary>Contexto técnico</summary><dl><div><dt>IP</dt><dd>{selected.ipAddress ?? 'Não informado'}</dd></div><div><dt>User agent</dt><dd>{selected.userAgent ?? 'Não informado'}</dd></div><div><dt>ID do log</dt><dd>{selected.id}</dd></div></dl></details></div></Modal>}
  </>;
}
