'use client';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/contexts/auth-context';
import { apiRequest } from '@/lib/api';
import type { LookupInput, LookupItem, LookupRelatedModule, LookupType } from '@/types/lookup';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/page-state';
import { Modal } from '@/components/ui/modal';
import { FormActions, PageHeader } from '@/components/ui/forms';

const tabs: {type:LookupType;label:string;text:string}[] = [
  {type:'UNIT',label:'Unidades',text:'Unidades organizacionais e suas siglas.'}, {type:'DEPARTMENT',label:'Setores',text:'Setores com unidade vinculada opcional.'},
  {type:'SERVICE_ORDER_CATEGORY',label:'Categorias de OS',text:'Classificação das ordens de serviço.'}, {type:'SYSTEM_PROCESS',label:'Sistemas/Processos',text:'Sistemas e processos atendidos.'},
  {type:'PROJECT_TYPE',label:'Tipos de Projeto',text:'Classificação dos projetos.'}, {type:'CANCELLATION_REASON',label:'Motivos de Cancelamento',text:'Motivos por módulo operacional.'},
];
const blank = (type:LookupType):LookupInput => ({type,name:'',code:'',description:'',parentId:null,relatedModule:null,isActive:true,sortOrder:null});

export default function LookupsPage(){
  const {can}=useAuth(); const canManage=can('LOOKUPS','manage');
  const [type,setType]=useState<LookupType>('UNIT'),[items,setItems]=useState<LookupItem[]>([]),[units,setUnits]=useState<LookupItem[]>([]),[search,setSearch]=useState('');
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<LookupItem|null|undefined>(undefined),[form,setForm]=useState<LookupInput>(blank(type)),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [rows,unitRows]=await Promise.all([apiRequest<LookupItem[]>(`/lookups?type=${type}`),type==='DEPARTMENT'?apiRequest<LookupItem[]>('/lookups/UNIT?isActive=true'):Promise.resolve([])]);setItems(rows);setUnits(unitRows)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível carregar os cadastros.')}finally{setLoading(false)}},[type]);
  useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>{const term=search.trim().toLocaleLowerCase('pt-BR');return term?items.filter(item=>[item.name,item.code,item.description,item.parent?.name].some(value=>value?.toLocaleLowerCase('pt-BR').includes(term))):items},[items,search]);
  function open(item?:LookupItem){setNotice('');setEditing(item??null);setForm(item?{type:item.type,name:item.name,code:item.code??'',description:item.description??'',parentId:item.parentId??null,relatedModule:item.relatedModule??null,isActive:item.isActive,sortOrder:item.sortOrder??null}:blank(type));}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{const body={...form,code:form.code||null,description:form.description||null,parentId:form.parentId||null,relatedModule:form.relatedModule||null,sortOrder:form.sortOrder??null};await apiRequest(editing?`/lookups/${editing.id}`:'/lookups',{method:editing?'PATCH':'POST',body});setEditing(undefined);setNotice(editing?'Cadastro atualizado com sucesso.':'Cadastro criado com sucesso.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível salvar o cadastro.')}finally{setSaving(false)}}
  async function status(item:LookupItem){setError('');try{await apiRequest(`/lookups/${item.id}/status`,{method:'PATCH',body:{isActive:!item.isActive}});setNotice(`${item.name} foi ${item.isActive?'inativado':'reativado'}.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível alterar o status.')}}
  const current=tabs.find(tab=>tab.type===type)!;
  return <><PageHeader title="Cadastros Auxiliares" text="Padronize opções usadas em ordens de serviço, projetos e relatórios." action={canManage?()=>open():undefined} label={canManage?'Novo cadastro':undefined}/>
    <div className="lookup-tabs" role="tablist">{tabs.map(tab=><button key={tab.type} role="tab" aria-selected={type===tab.type} className={type===tab.type?'active':''} onClick={()=>{setType(tab.type);setSearch('');setNotice('')}}>{tab.label}</button>)}</div>
    <section className="lookup-toolbar"><div><strong>{current.label}</strong><span>{current.text}</span></div><input aria-label="Buscar cadastro" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, código ou descrição"/></section>
    {notice&&<div className="alert success">{notice}</div>}{error&&<ErrorState message={error} retry={load}/>} {loading?<LoadingState/>:!visible.length?<EmptyState text={search?'Nenhum cadastro corresponde à busca.':'Nenhum item cadastrado neste grupo.'}/>:<div className="lookup-list">{visible.map(item=><article className="lookup-card" key={item.id}><div><div className="lookup-title"><h3>{item.name}</h3>{item.code&&<span>{item.code}</span>}<span className={`badge ${item.isActive?'user-active':'user-inactive'}`}>{item.isActive?'Ativo':'Inativo'}</span></div><p>{item.description||'Sem descrição.'}</p><small>{item.parent?`Unidade: ${item.parent.name}`:item.relatedModule?`Módulo: ${item.relatedModule}`:item.sortOrder!=null?`Ordem: ${item.sortOrder}`:'Sem vínculo adicional'}</small></div>{canManage&&<div className="lookup-actions"><button className="button ghost small" onClick={()=>open(item)}>Editar</button><button className={`button small ${item.isActive?'danger-ghost':'ghost'}`} onClick={()=>void status(item)}>{item.isActive?'Inativar':'Reativar'}</button></div>}</article>)}</div>}
    {editing!==undefined&&<Modal title={editing?'Editar cadastro':'Novo cadastro'} onClose={()=>setEditing(undefined)}><form className="form-grid" onSubmit={submit}>{error&&<div className="alert error span-2">{error}</div>}<label className="span-2">Nome<input required maxLength={180} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{type==='UNIT'&&<label>Código / sigla<input maxLength={50} value={form.code??''} onChange={e=>setForm({...form,code:e.target.value})}/></label>}<label>Ordem de exibição<input type="number" min={0} value={form.sortOrder??''} onChange={e=>setForm({...form,sortOrder:e.target.value===''?null:Number(e.target.value)})}/></label>{type==='DEPARTMENT'&&<label className="span-2">Unidade vinculada<select value={form.parentId??''} onChange={e=>setForm({...form,parentId:e.target.value||null})}><option value="">Nenhuma</option>{units.map(unit=><option value={unit.id} key={unit.id}>{unit.name}</option>)}</select></label>}{type==='CANCELLATION_REASON'&&<label className="span-2">Módulo relacionado<select value={form.relatedModule??''} onChange={e=>setForm({...form,relatedModule:(e.target.value||null) as LookupRelatedModule|null})}><option value="">Todos / não informado</option><option value="SERVICE_ORDER">Ordem de Serviço</option><option value="PROJECT">Projeto</option><option value="TASK">Tarefa</option></select></label>}<label className="span-2">Descrição<textarea maxLength={1000} value={form.description??''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="lookup-active span-2"><input type="checkbox" checked={form.isActive??true} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Cadastro ativo</label><FormActions saving={saving} close={()=>setEditing(undefined)}/></form></Modal>}
  </>;
}
