'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { PublicAuthCard } from '@/components/auth/public-auth-card';
import { apiRequest } from '@/lib/api';
type RegistrationSettings={enabled:boolean;allowedEmailDomain:string;environmentName:string|null;institutionName:string|null};
export default function RegisterPage(){
 const[form,setForm]=useState({name:'',email:'',password:'',confirmation:''}),[error,setError]=useState(''),[success,setSuccess]=useState(''),[loading,setLoading]=useState(false),[settings,setSettings]=useState<RegistrationSettings|null>(null);
 useEffect(()=>{apiRequest<RegistrationSettings>('/auth/requester-registration-settings',{authenticated:false}).then(setSettings).catch(reason=>setError(reason instanceof Error?reason.message:'Não foi possível consultar a disponibilidade do cadastro.'))},[]);
 async function submit(e:FormEvent){e.preventDefault();setError('');setSuccess('');if(form.password!==form.confirmation)return setError('A confirmação de senha não corresponde.');setLoading(true);try{const r=await apiRequest<{message:string}>('/auth/register-requester',{method:'POST',authenticated:false,body:{name:form.name,email:form.email,password:form.password}});setSuccess(r.message);setForm({name:'',email:'',password:'',confirmation:''})}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível concluir o cadastro.')}finally{setLoading(false)}}
 return <PublicAuthCard eyebrow="Autocadastro institucional" title="Cadastrar-me como solicitante" text="Crie seu acesso para abrir e acompanhar ordens de serviço. O cadastro dá acesso somente ao Portal do Solicitante.">{error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success} <Link href="/login">Entrar agora</Link></div>}{settings&&!settings.enabled?<><div className="alert warning">O autocadastro está temporariamente desativado. Solicite acesso ao administrador do ambiente.</div><p className="auth-back-link"><Link href="/login">Voltar ao login</Link></p></>:<form className="public-auth-form" onSubmit={submit}><label>Nome completo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} minLength={2} maxLength={180} required autoFocus/></label><label>E-mail institucional<input type="email" placeholder={`nome@${settings?.allowedEmailDomain??'colsan.org.br'}`} value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Senha<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={8} maxLength={72} required/></label><small className="password-hint">Use ao menos 8 caracteres, com letras, números e caractere especial.</small><label>Confirmar senha<input type="password" value={form.confirmation} onChange={e=>setForm({...form,confirmation:e.target.value})} minLength={8} required/></label><button className="button primary full" disabled={loading||!settings}>{loading?'Criando acesso...':'Criar acesso'}</button></form>}</PublicAuthCard>;
}
