'use client';
import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { apiDownload, apiRequest } from '@/lib/api';
import type { ServiceOrderAttachment, ServiceOrderComment } from '@/types/service-order';
type TargetType = 'service-order' | 'project' | 'task';
const message = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;
const dateTime = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const fileSize = (value: number) => value < 1048576 ? `${Math.max(1, Math.round(value / 1024))} KB` : `${(value / 1048576).toFixed(1)} MB`;
export function TargetPanels({ targetType, targetId, canContribute }: { targetType: TargetType; targetId: string; canContribute: boolean }) {
  const [comments, setComments] = useState<ServiceOrderComment[]>([]); const [attachments, setAttachments] = useState<ServiceOrderAttachment[]>([]);
  const [text, setText] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const input = useRef<HTMLInputElement>(null); const base = targetType === 'service-order' ? 'service-order' : targetType;
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextComments, nextAttachments] = await Promise.all([apiRequest<ServiceOrderComment[]>(`/comments/${base}/${targetId}`), apiRequest<ServiceOrderAttachment[]>(`/attachments/${base}/${targetId}`)]); setComments(nextComments); setAttachments(nextAttachments); } catch (reason) { setError(message(reason, 'Não foi possível carregar comentários e anexos.')); } finally { setLoading(false); } }, [base, targetId]);
  useEffect(() => { void load(); }, [load]);
  async function comment(event: FormEvent) { event.preventDefault(); if (!text.trim()) return; setSaving(true); setError(''); try { await apiRequest(`/comments/${base}/${targetId}`, { method: 'POST', body: { text: text.trim() } }); setText(''); await load(); } catch (reason) { setError(message(reason, 'Não foi possível adicionar o comentário.')); } finally { setSaving(false); } }
  async function upload(file?: File) { if (!file) return; setSaving(true); setError(''); const body = new FormData(); body.append('file', file); try { await apiRequest(`/attachments/${base}/${targetId}`, { method: 'POST', body }); if (input.current) input.current.value = ''; await load(); } catch (reason) { setError(message(reason, 'Não foi possível enviar o anexo.')); } finally { setSaving(false); } }
  return <>
    <section className="detail-card"><div className="section-head"><div><h2>Comentários</h2><p>Acompanhe o histórico e registre atualizações.</p></div><span>{comments.length}</span></div>{error && <div className="alert error" role="alert">{error}</div>}{canContribute && <form className="comment-form" onSubmit={comment}><textarea rows={4} maxLength={5000} value={text} onChange={(event) => setText(event.target.value)} placeholder="Escreva um comentário..." aria-label="Novo comentário" /><div><small>{text.length}/5000</small><button className="button primary" disabled={saving || !text.trim()}>{saving ? 'Publicando...' : 'Adicionar comentário'}</button></div></form>}<div className="comment-list">{loading ? <p className="inline-empty">Carregando comentários...</p> : comments.length ? comments.map((item) => <article className="comment" key={item.id}><span className="avatar">{item.author.name.slice(0, 2)}</span><div><header><strong>{item.author.name}</strong><time dateTime={item.createdAt}>{dateTime(item.createdAt)}</time></header><p>{item.text}</p></div></article>) : <p className="inline-empty">Ainda não há comentários.</p>}</div></section>
    <section className="detail-card"><div className="section-head"><div><h2>Anexos</h2><p>Documentos e imagens vinculados a este item.</p></div><span>{attachments.length}</span></div>{canContribute && <label className="upload-box"><input ref={input} type="file" disabled={saving} accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx,.xls,.xlsx,.csv,.txt" onChange={(event) => void upload(event.target.files?.[0])} /><strong>{saving ? 'Enviando arquivo...' : 'Enviar anexo'}</strong><small>Documentos ou imagens de até 10 MB</small></label>}<div className="attachment-list">{loading ? <p className="inline-empty">Carregando anexos...</p> : attachments.length ? attachments.map((item) => { const name = item.originalName || item.fileName; return <article className="attachment" key={item.id}><span>⇩</span><div><strong>{name}</strong><small>{fileSize(item.size)} · enviado por {item.uploadedBy.name} · {dateTime(item.createdAt)}</small></div><button type="button" className="button ghost small" onClick={() => void apiDownload(`/attachments/${item.id}/download`, name).catch((reason) => setError(message(reason, 'Erro no download.')))}>Baixar</button></article>; }) : <p className="inline-empty">Nenhum anexo enviado.</p>}</div></section>
  </>;
}
